# Generated by Django 6.0.3 on 2026-04-05 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('brand', 'Brand'), ('ram', 'RAM'), ('memory', 'Memory'), ('color', 'Color')], max_length=20)),
                ('value', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('release_year', models.PositiveIntegerField()),
                ('display_size', models.CharField(max_length=20)),
                ('resolution', models.CharField(max_length=50)),
                ('cpu', models.CharField(max_length=50)),
                ('rear_camera', models.CharField(max_length=100)),
                ('front_camera', models.CharField(max_length=50)),
                ('battery', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('material', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(limit_choices_to={'type': 'brand'}, on_delete=django.db.models.deletion.PROTECT, related_name='brand_phones', to='home.reference')),
                ('color', models.ForeignKey(limit_choices_to={'type': 'color'}, on_delete=django.db.models.deletion.PROTECT, related_name='color_phones', to='home.reference')),
                ('memory', models.ForeignKey(limit_choices_to={'type': 'memory'}, on_delete=django.db.models.deletion.PROTECT, related_name='memory_phones', to='home.reference')),
                ('ram', models.ForeignKey(limit_choices_to={'type': 'ram'}, on_delete=django.db.models.deletion.PROTECT, related_name='ram_phones', to='home.reference')),
            ],
        ),
    ]
