# Generated by Django 6.0.3 on 2026-04-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
