# Generated by Django 6.0.3 on 2026-04-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_phone_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='picture',
            field=models.FileField(default=1, upload_to='images/phone_photos'),
            preserve_default=False,
        ),
    ]
