# Generated by Django 6.0.4 on 2026-04-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_phone_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
