# Generated by Django 6.0.4 on 2026-04-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_phone_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
