# Generated by Django 6.0.4 on 2026-04-11 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_staff_alter_phone_description_purchase_sale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Stuff',
        ),
    ]
