# Generated by Django 6.0.4 on 2026-04-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_staff_stuff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='staff',
        ),
    ]
