# Generated by Django 6.0.4 on 2026-04-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_sale_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
