# Generated by Django 6.0.4 on 2026-04-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_sale_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
