# Generated by Django 6.0.4 on 2026-04-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_stuff_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
