# Generated by Django 6.0.4 on 2026-04-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_stuff_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
