# Generated by Django 6.0.4 on 2026-04-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_phone_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cost_price',
            field=models.DecimalField(decimal_places=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price_sold',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='salary',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
